replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/tmgalaxy/astra-testnet/astra-frontend
  pullPolicy: IfNotPresent
  tag: "1234567"

serviceAccount:
  create: true
  automount: false
  name: "astra-frontend"

service:
  type: LoadBalancer
  port: 8080
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "astra-backendconfig"}'

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.gcp.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: astradao.org
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
  - secretName: astra-mainnet-tls
    hosts:
      - astradao.org
      
resources:
  requests:
    memory: "300Mi"
    cpu: "200m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumeMounts:
  - name: data-volume
    mountPath: /data

volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: astradao-pvc

pvc:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: standard-rwo

backendConfig:
  namespace: astra-mainnet
  securityPolicy:
    name: "ddos-policy-alpha-us-central1"