replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/tmgalaxy/tokenmetrics-prod/astra-frontend
  pullPolicy: IfNotPresent
  tag: "1234567"

serviceAccount:
  create: true
  automount: false
  name: "astra-frontend"

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: astradao.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: astra-mainnet-tls
    hosts:
      - astradao.org

resources:
  requests:
    memory: "500Mi"
    cpu: "400m"

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumeMounts:
  - name: data-volume
    mountPath: /data

volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: astradao-pvc

pvc:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: standard-rwo

backendConfig:
  namespace: astra-mainnet