replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/tmgalaxy/astra-testnet/astra-frontend
  pullPolicy: IfNotPresent
  tag: testnet-10eca74

serviceAccount:
  create: true
  automount: false
  name: "astra-frontend"

service:
  type: LoadBalancer
  port: 8080
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "astra-backendconfig"}'

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.gcp.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: gce
    # networking.gke.io/v1beta1.FrontendConfig: "astra-frontend"
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: next.test.astradao.org
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls:
  - secretName: astra-frontend-tls
    hosts:
      - next.test.astradao.org

resources:
  requests:
    memory: "200Mi"
    cpu: "100m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

pvc:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: standard-rwo

backendConfig:
  namespace: astra-testnet
  securityPolicy:
    name: "ddos-policy-alpha-us-central1"