name: Code Quality Gate - SonarQube

on:
  push:
    branches:
      - master # prod
      - development # alpha
      - feature/**
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
      - development
      - feature/**

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch: ${{ github.REF }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.HEAD_REF }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
    
      - name: Install dependencies
        run: npm install . --force

      - name: Lint Project
        run: npm run lint
      # - run: npm run test

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




        

  write-creds-from-secrets:
    name: "Write env from secrets"
    runs-on: ubuntu-latest
    needs: [sonar-scan]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Write .env.production from secrets
        if: ${{ steps.branch-names.outputs.ref_branch == 'master' }}
        id: prod_creds
        run: |
          echo "${{ secrets.TM_ENV_PROD }}" > .env
        env:
          TM_ENV_PROD: ${{ secrets.TM_ENV_PROD }}

      - name: Write .env.development from secrets
        if: ${{ steps.branch-names.outputs.ref_branch == 'development' || 'feature/**'}}
        id: dev_creds
        run: |
          echo "${{ secrets.TM_ENV_DEV }}" > .env
        env:
          TM_ENV_DEV: ${{ secrets.TM_ENV_DEV }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: creds-artifact
          path: |
            .env

      - name: Ensure .env.production.dist is correctly outputed
        run: cat .env

  docker-build-and-push:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    needs: [sonar-scan, write-creds-from-secrets]

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: creds-artifact
          path: ./

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Build docker image
        if: (${{ steps.branch-names.outputs.ref_branch != 'master' }}) && (github.event_name == 'pull_request')
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

          cd ./
          ls -la
          cat .env
          docker build -t us-central1-docker.pkg.dev/tmgalaxy/tm-de-artifact/tm-front:${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}-${GITHUB_SHA::7} .

      - name: Push image to dev repo if branch is development
        if: (github.ref == 'refs/heads/development') && (github.event.pull_request.merged == true || github.event_name == 'push')
        run: |
          docker push us-central1-docker.pkg.dev/tmgalaxy/tm-de-artifact/tm-front:${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}-${GITHUB_SHA::7}

      # Push to prod artifact repository
      - name: Build docker image
        if: ${{ steps.branch-names.outputs.ref_branch == 'master' }} && (github.event_name == 'pull_request')
        run: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            cd ./
            ls -la
            cat .env
            docker build -t us-central1-docker.pkg.dev/tmgalaxy/tokenmetrics-prod/tm-front:${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}-${GITHUB_SHA::7} .

      - name: Push image to prod repo if branch is master
        if: (github.ref == 'refs/heads/master') && (github.event.pull_request.merged == true || github.event_name == 'push')
        run: |
          docker push us-central1-docker.pkg.dev/tmgalaxy/tokenmetrics-prod/tm-front:${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}-${GITHUB_SHA::7}

  release-to-k8s:
    name: "Release to k8s"
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]

    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud

        uses: google-github-actions/auth@v2
        with:
            credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

        # get alpha cluster creds
      - name: "Get GKE alpha credentials"
        if: ${{ steps.branch-names.outputs.ref_branch != 'master' }}
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
            cluster_name: "cluster-alpha-us-central1"
            location: "us-central1"

        # get prod cluster creds
      - name: "Get GKE prod credentials"
        if: ${{ steps.branch-names.outputs.ref_branch == 'master' }}
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
            cluster_name: "cluster-prod-us-central1"
            location: "us-central1"

      - name: Deploy to cluster
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development') && (github.event.pull_request.merged == true || github.event_name == 'push')
        run: |
            helm upgrade --install astra-frontend ./helm/my_helm-chart \
            --namespace astra-frontend \
            --values ./helm/values.yaml \
            --values ./helm/helmvars/${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}/values.yaml \
            --set image.tag=${{ steps.branch-names.outputs.ref_branch == 'master' && 'prod' || 'alpha'}}-${GITHUB_SHA::7} \
            --timeout 5m0s --create-namespace --debug


            





